package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CommandeClient generated by hbm2java
 */
public class CommandeClient implements java.io.Serializable {

	private Integer idCmdClt;
	private BonDeLivraison bonDeLivraison;
	private Client client;
	private Facture facture;
	private Date dateCmdClt;
	private int prixTotalClt;
	private Set factures = new HashSet(0);
	private Set ligneCmdClts = new HashSet(0);
	private Set bonDeLivraisons = new HashSet(0);

	public CommandeClient() {
	}

	public CommandeClient(BonDeLivraison bonDeLivraison, Client client, Facture facture, Date dateCmdClt,
			int prixTotalClt) {
		this.bonDeLivraison = bonDeLivraison;
		this.client = client;
		this.facture = facture;
		this.dateCmdClt = dateCmdClt;
		this.prixTotalClt = prixTotalClt;
	}

	public CommandeClient(BonDeLivraison bonDeLivraison, Client client, Facture facture, Date dateCmdClt,
			int prixTotalClt, Set factures, Set ligneCmdClts, Set bonDeLivraisons) {
		this.bonDeLivraison = bonDeLivraison;
		this.client = client;
		this.facture = facture;
		this.dateCmdClt = dateCmdClt;
		this.prixTotalClt = prixTotalClt;
		this.factures = factures;
		this.ligneCmdClts = ligneCmdClts;
		this.bonDeLivraisons = bonDeLivraisons;
	}

	public Integer getIdCmdClt() {
		return this.idCmdClt;
	}

	public void setIdCmdClt(Integer idCmdClt) {
		this.idCmdClt = idCmdClt;
	}

	public BonDeLivraison getBonDeLivraison() {
		return this.bonDeLivraison;
	}

	public void setBonDeLivraison(BonDeLivraison bonDeLivraison) {
		this.bonDeLivraison = bonDeLivraison;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	public Date getDateCmdClt() {
		return this.dateCmdClt;
	}

	public void setDateCmdClt(Date dateCmdClt) {
		this.dateCmdClt = dateCmdClt;
	}

	public int getPrixTotalClt() {
		return this.prixTotalClt;
	}

	public void setPrixTotalClt(int prixTotalClt) {
		this.prixTotalClt = prixTotalClt;
	}

	public Set getFactures() {
		return this.factures;
	}

	public void setFactures(Set factures) {
		this.factures = factures;
	}

	public Set getLigneCmdClts() {
		return this.ligneCmdClts;
	}

	public void setLigneCmdClts(Set ligneCmdClts) {
		this.ligneCmdClts = ligneCmdClts;
	}

	public Set getBonDeLivraisons() {
		return this.bonDeLivraisons;
	}

	public void setBonDeLivraisons(Set bonDeLivraisons) {
		this.bonDeLivraisons = bonDeLivraisons;
	}

}
