package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CommandeFournisseur generated by hbm2java
 */
public class CommandeFournisseur implements java.io.Serializable {

	private Integer idCmdFounisseur;
	private Facture facture;
	private Date dateCmdFounisseur;
	private int prixTotalFournisseur;
	private Set ligneCmdFounisseurs = new HashSet(0);

	public CommandeFournisseur() {
	}

	public CommandeFournisseur(Facture facture, Date dateCmdFounisseur, int prixTotalFournisseur) {
		this.facture = facture;
		this.dateCmdFounisseur = dateCmdFounisseur;
		this.prixTotalFournisseur = prixTotalFournisseur;
	}

	public CommandeFournisseur(Facture facture, Date dateCmdFounisseur, int prixTotalFournisseur,
			Set ligneCmdFounisseurs) {
		this.facture = facture;
		this.dateCmdFounisseur = dateCmdFounisseur;
		this.prixTotalFournisseur = prixTotalFournisseur;
		this.ligneCmdFounisseurs = ligneCmdFounisseurs;
	}

	public Integer getIdCmdFounisseur() {
		return this.idCmdFounisseur;
	}

	public void setIdCmdFounisseur(Integer idCmdFounisseur) {
		this.idCmdFounisseur = idCmdFounisseur;
	}

	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	public Date getDateCmdFounisseur() {
		return this.dateCmdFounisseur;
	}

	public void setDateCmdFounisseur(Date dateCmdFounisseur) {
		this.dateCmdFounisseur = dateCmdFounisseur;
	}

	public int getPrixTotalFournisseur() {
		return this.prixTotalFournisseur;
	}

	public void setPrixTotalFournisseur(int prixTotalFournisseur) {
		this.prixTotalFournisseur = prixTotalFournisseur;
	}

	public Set getLigneCmdFounisseurs() {
		return this.ligneCmdFounisseurs;
	}

	public void setLigneCmdFounisseurs(Set ligneCmdFounisseurs) {
		this.ligneCmdFounisseurs = ligneCmdFounisseurs;
	}

}
