package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur implements java.io.Serializable {

	private Integer idFournisseur;
	private String nomFournisseur;
	private String addrFournisseur;
	private String telFournisseur;
	private Set produits = new HashSet(0);

	public Fournisseur() {
	}

	public Fournisseur(String nomFournisseur, String addrFournisseur, String telFournisseur) {
		this.nomFournisseur = nomFournisseur;
		this.addrFournisseur = addrFournisseur;
		this.telFournisseur = telFournisseur;
	}

	public Fournisseur(String nomFournisseur, String addrFournisseur, String telFournisseur, Set produits) {
		this.nomFournisseur = nomFournisseur;
		this.addrFournisseur = addrFournisseur;
		this.telFournisseur = telFournisseur;
		this.produits = produits;
	}

	public Integer getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(Integer idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	public String getNomFournisseur() {
		return this.nomFournisseur;
	}

	public void setNomFournisseur(String nomFournisseur) {
		this.nomFournisseur = nomFournisseur;
	}

	public String getAddrFournisseur() {
		return this.addrFournisseur;
	}

	public void setAddrFournisseur(String addrFournisseur) {
		this.addrFournisseur = addrFournisseur;
	}

	public String getTelFournisseur() {
		return this.telFournisseur;
	}

	public void setTelFournisseur(String telFournisseur) {
		this.telFournisseur = telFournisseur;
	}

	public Set getProduits() {
		return this.produits;
	}

	public void setProduits(Set produits) {
		this.produits = produits;
	}

}
