package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

/**
 * LigneCmdFounisseur generated by hbm2java
 */
public class LigneCmdFounisseur implements java.io.Serializable {

	private LigneCmdFounisseurId id;
	private CommandeFournisseur commandeFournisseur;
	private Produit produit;

	public LigneCmdFounisseur() {
	}

	public LigneCmdFounisseur(LigneCmdFounisseurId id, CommandeFournisseur commandeFournisseur, Produit produit) {
		this.id = id;
		this.commandeFournisseur = commandeFournisseur;
		this.produit = produit;
	}

	public LigneCmdFounisseurId getId() {
		return this.id;
	}

	public void setId(LigneCmdFounisseurId id) {
		this.id = id;
	}

	public CommandeFournisseur getCommandeFournisseur() {
		return this.commandeFournisseur;
	}

	public void setCommandeFournisseur(CommandeFournisseur commandeFournisseur) {
		this.commandeFournisseur = commandeFournisseur;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

}
