package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

/**
 * LigneCmdFounisseurId generated by hbm2java
 */
public class LigneCmdFounisseurId implements java.io.Serializable {

	private int refProduit;
	private int idCmdFournisseur;
	private int qtPrdCmd;

	public LigneCmdFounisseurId() {
	}

	public LigneCmdFounisseurId(int refProduit, int idCmdFournisseur, int qtPrdCmd) {
		this.refProduit = refProduit;
		this.idCmdFournisseur = idCmdFournisseur;
		this.qtPrdCmd = qtPrdCmd;
	}

	public int getRefProduit() {
		return this.refProduit;
	}

	public void setRefProduit(int refProduit) {
		this.refProduit = refProduit;
	}

	public int getIdCmdFournisseur() {
		return this.idCmdFournisseur;
	}

	public void setIdCmdFournisseur(int idCmdFournisseur) {
		this.idCmdFournisseur = idCmdFournisseur;
	}

	public int getQtPrdCmd() {
		return this.qtPrdCmd;
	}

	public void setQtPrdCmd(int qtPrdCmd) {
		this.qtPrdCmd = qtPrdCmd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LigneCmdFounisseurId))
			return false;
		LigneCmdFounisseurId castOther = (LigneCmdFounisseurId) other;

		return (this.getRefProduit() == castOther.getRefProduit())
				&& (this.getIdCmdFournisseur() == castOther.getIdCmdFournisseur())
				&& (this.getQtPrdCmd() == castOther.getQtPrdCmd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRefProduit();
		result = 37 * result + this.getIdCmdFournisseur();
		result = 37 * result + this.getQtPrdCmd();
		return result;
	}

}
