package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit implements java.io.Serializable {

	private Integer refProduit;
	private Categorie categorie;
	private Fournisseur fournisseur;
	private String designationProduit;
	private int quantiteProduit;
	private float prixProduit;
	private int seuilMin;
	private String imageProduit;
	private Set ligneCmdClts = new HashSet(0);
	private Set ligneCmdFounisseurs = new HashSet(0);

	public Produit() {
	}

	public Produit(Categorie categorie, Fournisseur fournisseur, String designationProduit, int quantiteProduit,
			float prixProduit, int seuilMin, String imageProduit) {
		this.categorie = categorie;
		this.fournisseur = fournisseur;
		this.designationProduit = designationProduit;
		this.quantiteProduit = quantiteProduit;
		this.prixProduit = prixProduit;
		this.seuilMin = seuilMin;
		this.imageProduit = imageProduit;
	}

	public Produit(Categorie categorie, Fournisseur fournisseur, String designationProduit, int quantiteProduit,
			float prixProduit, int seuilMin, String imageProduit, Set ligneCmdClts, Set ligneCmdFounisseurs) {
		this.categorie = categorie;
		this.fournisseur = fournisseur;
		this.designationProduit = designationProduit;
		this.quantiteProduit = quantiteProduit;
		this.prixProduit = prixProduit;
		this.seuilMin = seuilMin;
		this.imageProduit = imageProduit;
		this.ligneCmdClts = ligneCmdClts;
		this.ligneCmdFounisseurs = ligneCmdFounisseurs;
	}

	public Integer getRefProduit() {
		return this.refProduit;
	}

	public void setRefProduit(Integer refProduit) {
		this.refProduit = refProduit;
	}

	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	public String getDesignationProduit() {
		return this.designationProduit;
	}

	public void setDesignationProduit(String designationProduit) {
		this.designationProduit = designationProduit;
	}

	public int getQuantiteProduit() {
		return this.quantiteProduit;
	}

	public void setQuantiteProduit(int quantiteProduit) {
		this.quantiteProduit = quantiteProduit;
	}

	public float getPrixProduit() {
		return this.prixProduit;
	}

	public void setPrixProduit(float prixProduit) {
		this.prixProduit = prixProduit;
	}

	public int getSeuilMin() {
		return this.seuilMin;
	}

	public void setSeuilMin(int seuilMin) {
		this.seuilMin = seuilMin;
	}

	public String getImageProduit() {
		return this.imageProduit;
	}

	public void setImageProduit(String imageProduit) {
		this.imageProduit = imageProduit;
	}

	public Set getLigneCmdClts() {
		return this.ligneCmdClts;
	}

	public void setLigneCmdClts(Set ligneCmdClts) {
		this.ligneCmdClts = ligneCmdClts;
	}

	public Set getLigneCmdFounisseurs() {
		return this.ligneCmdFounisseurs;
	}

	public void setLigneCmdFounisseurs(Set ligneCmdFounisseurs) {
		this.ligneCmdFounisseurs = ligneCmdFounisseurs;
	}

}
