package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BonDeLivraison generated by hbm2java
 */
public class BonDeLivraison implements java.io.Serializable {

	private Integer idLivraison;
	private CommandeClient commandeClient;
	private Date dateLivraison;
	private int qtLivraison;
	private float mntLivraison;
	private Set commandeClients = new HashSet(0);

	public BonDeLivraison() {
	}

	public BonDeLivraison(CommandeClient commandeClient, Date dateLivraison, int qtLivraison, float mntLivraison) {
		this.commandeClient = commandeClient;
		this.dateLivraison = dateLivraison;
		this.qtLivraison = qtLivraison;
		this.mntLivraison = mntLivraison;
	}

	public BonDeLivraison(CommandeClient commandeClient, Date dateLivraison, int qtLivraison, float mntLivraison,
			Set commandeClients) {
		this.commandeClient = commandeClient;
		this.dateLivraison = dateLivraison;
		this.qtLivraison = qtLivraison;
		this.mntLivraison = mntLivraison;
		this.commandeClients = commandeClients;
	}

	public Integer getIdLivraison() {
		return this.idLivraison;
	}

	public void setIdLivraison(Integer idLivraison) {
		this.idLivraison = idLivraison;
	}

	public CommandeClient getCommandeClient() {
		return this.commandeClient;
	}

	public void setCommandeClient(CommandeClient commandeClient) {
		this.commandeClient = commandeClient;
	}

	public Date getDateLivraison() {
		return this.dateLivraison;
	}

	public void setDateLivraison(Date dateLivraison) {
		this.dateLivraison = dateLivraison;
	}

	public int getQtLivraison() {
		return this.qtLivraison;
	}

	public void setQtLivraison(int qtLivraison) {
		this.qtLivraison = qtLivraison;
	}

	public float getMntLivraison() {
		return this.mntLivraison;
	}

	public void setMntLivraison(float mntLivraison) {
		this.mntLivraison = mntLivraison;
	}

	public Set getCommandeClients() {
		return this.commandeClients;
	}

	public void setCommandeClients(Set commandeClients) {
		this.commandeClients = commandeClients;
	}

}
