package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer idClient;
	private String nomClient;
	private String addrClient;
	private String telClient;
	private Set commandeClients = new HashSet(0);

	public Client() {
	}

	public Client(String nomClient, String addrClient, String telClient) {
		this.nomClient = nomClient;
		this.addrClient = addrClient;
		this.telClient = telClient;
	}

	public Client(String nomClient, String addrClient, String telClient, Set commandeClients) {
		this.nomClient = nomClient;
		this.addrClient = addrClient;
		this.telClient = telClient;
		this.commandeClients = commandeClients;
	}

	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	public String getNomClient() {
		return this.nomClient;
	}

	public void setNomClient(String nomClient) {
		this.nomClient = nomClient;
	}

	public String getAddrClient() {
		return this.addrClient;
	}

	public void setAddrClient(String addrClient) {
		this.addrClient = addrClient;
	}

	public String getTelClient() {
		return this.telClient;
	}

	public void setTelClient(String telClient) {
		this.telClient = telClient;
	}

	public Set getCommandeClients() {
		return this.commandeClients;
	}

	public void setCommandeClients(Set commandeClients) {
		this.commandeClients = commandeClients;
	}

}
