package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facture generated by hbm2java
 */
public class Facture implements java.io.Serializable {

	private Integer idFacture;
	private CommandeClient commandeClient;
	private Date dateFacture;
	private Date dateLimite;
	private float mntTotal;
	private Set commandeFournisseurs = new HashSet(0);
	private Set commandeClients = new HashSet(0);

	public Facture() {
	}

	public Facture(CommandeClient commandeClient, Date dateFacture, Date dateLimite, float mntTotal) {
		this.commandeClient = commandeClient;
		this.dateFacture = dateFacture;
		this.dateLimite = dateLimite;
		this.mntTotal = mntTotal;
	}

	public Facture(CommandeClient commandeClient, Date dateFacture, Date dateLimite, float mntTotal,
			Set commandeFournisseurs, Set commandeClients) {
		this.commandeClient = commandeClient;
		this.dateFacture = dateFacture;
		this.dateLimite = dateLimite;
		this.mntTotal = mntTotal;
		this.commandeFournisseurs = commandeFournisseurs;
		this.commandeClients = commandeClients;
	}

	public Integer getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(Integer idFacture) {
		this.idFacture = idFacture;
	}

	public CommandeClient getCommandeClient() {
		return this.commandeClient;
	}

	public void setCommandeClient(CommandeClient commandeClient) {
		this.commandeClient = commandeClient;
	}

	public Date getDateFacture() {
		return this.dateFacture;
	}

	public void setDateFacture(Date dateFacture) {
		this.dateFacture = dateFacture;
	}

	public Date getDateLimite() {
		return this.dateLimite;
	}

	public void setDateLimite(Date dateLimite) {
		this.dateLimite = dateLimite;
	}

	public float getMntTotal() {
		return this.mntTotal;
	}

	public void setMntTotal(float mntTotal) {
		this.mntTotal = mntTotal;
	}

	public Set getCommandeFournisseurs() {
		return this.commandeFournisseurs;
	}

	public void setCommandeFournisseurs(Set commandeFournisseurs) {
		this.commandeFournisseurs = commandeFournisseurs;
	}

	public Set getCommandeClients() {
		return this.commandeClients;
	}

	public void setCommandeClients(Set commandeClients) {
		this.commandeClients = commandeClients;
	}

}
