package ma.ensa.model;
// Generated 18 déc. 2016 21:13:46 by Hibernate Tools 5.2.0.CR1

/**
 * LigneCmdCltId generated by hbm2java
 */
public class LigneCmdCltId implements java.io.Serializable {

	private int idCmdClt;
	private int refProduit;
	private int qtCmdClt;

	public LigneCmdCltId() {
	}

	public LigneCmdCltId(int idCmdClt, int refProduit, int qtCmdClt) {
		this.idCmdClt = idCmdClt;
		this.refProduit = refProduit;
		this.qtCmdClt = qtCmdClt;
	}

	public int getIdCmdClt() {
		return this.idCmdClt;
	}

	public void setIdCmdClt(int idCmdClt) {
		this.idCmdClt = idCmdClt;
	}

	public int getRefProduit() {
		return this.refProduit;
	}

	public void setRefProduit(int refProduit) {
		this.refProduit = refProduit;
	}

	public int getQtCmdClt() {
		return this.qtCmdClt;
	}

	public void setQtCmdClt(int qtCmdClt) {
		this.qtCmdClt = qtCmdClt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LigneCmdCltId))
			return false;
		LigneCmdCltId castOther = (LigneCmdCltId) other;

		return (this.getIdCmdClt() == castOther.getIdCmdClt()) && (this.getRefProduit() == castOther.getRefProduit())
				&& (this.getQtCmdClt() == castOther.getQtCmdClt());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCmdClt();
		result = 37 * result + this.getRefProduit();
		result = 37 * result + this.getQtCmdClt();
		return result;
	}

}
